### ISSUE TITLE
现在在 chrome商店怎么没有了？被下架了？

### ISSUE THREAD

**Issue by meicuihui** [justjavac/ChromeSnifferPlus#109]
[https://chrome.google.com/webstore/detail/library-sniffer-for-googl/fhhdlnnepfjhlhilgmeepgkhjmhhhjkh](https://chrome.google.com/webstore/detail/library-sniffer-for-googl/fhhdlnnepfjhlhilgmeepgkhjmhhhjkh)

**Comment by justjavac** [comment]
新版正在审核

**Comment by dalianmaoaichiyu** [comment]
谢谢

**Comment by cikichen** [comment]
貌似还没上架呢

**Comment by justjavac** [comment]
上不去了，已经被驳回3次了。说是我描述里面关键字太多

**Comment by ijrou** [comment]
**咦？难道已经不能上去了么？**

**Comment by jqw1992** [comment]
我说怎么下架了。
如果找不到可以去 chromefor.com 下载

**Comment by justjavac** [comment]
一周过去了，居然一直被驳回

**Comment by jqw1992** [comment]
现在 严格了吧。以前很多 挂马的插件在上面

**Comment by zhw2590582** [comment]
突然用不了，好不习惯

**Comment by justjavac** [comment]
周末又重新提交了一版

**Comment by justjavac** [comment]
已经上线了
