### ISSUE TITLE
codeigniter框架

### ISSUE THREAD

**Issue by qinshou** [justjavac/ChromeSnifferPlus#14]
如果网站使用了PHP的codeigniter框架，访问URL包含 " ! " 或者 " - "，会返回400和一个“CI化”的错误页面。CI特有的内置、全局判断规则..

例：
 http://codeigniter.org.cn/!
http://www.php230.com/!
http://v.ganlu.us/stats/mtmain/!

官方案例：http://codeigniter.org.cn/projects

**Comment by justjavac** [comment]
增加了根据cookies检测ci框架
