### ISSUE TITLE
不知道priority具体是怎么定义法？能否给出个参考标准？

### ISSUE THREAD

**Issue by spacewander** [justjavac/ChromeSnifferPlus#30]
就是指`apps.js`中每个应用的priority。
现在只能参照已有的应用来定义priority，但是每个人的观点不一定能够统一，其所秉持的参照点也可能各不相同。
不知可否提供一套详细的规则，以方便contributers添加明确的应用信息？

**Comment by justjavac** [comment]
下一版本会去掉这个，按字母顺序排列
