### ISSUE TITLE
Bootstrap的链接建议修改为http://getbootstrap.com/

### ISSUE THREAD

**Issue by str2code** [justjavac/ChromeSnifferPlus#37]
http://twitter.github.com/bootstrap/ 会跳转到老版本地址，http://getbootstrap.com/ 首页是最新版！

**Comment by str2code** [comment]
链接还是2.3的链接（谷歌商城安装）！

**Comment by justjavac** [comment]
@str2code 我会尽快修改一下。谢谢。

最近一直忙其他项目，这个好久没有更新了。
