### ISSUE TITLE
多余的日志可以去掉吗

### ISSUE THREAD

**Issue by debbbbie** [justjavac/ChromeSnifferPlus#45]
经常需要调试页面，老看到这两行日志，可以去掉不，多谢

![image](https://cloud.githubusercontent.com/assets/233115/8722470/9a416640-2bf7-11e5-88ae-fea4cb4e2c4a.png)

**Comment by justjavac** [comment]
你用的是正式发布版吗？

**Comment by debbbbie** [comment]
@justjavac 对啊，从chrome商店下的，当前版本：1.2.0

**Comment by debbbbie** [comment]
![image](https://cloud.githubusercontent.com/assets/233115/8741705/69954b68-2c8f-11e5-9239-36bc87df431d.png)

**Comment by debbbbie** [comment]
:+1:
