### ISSUE TITLE
It can't work at the chrome 49 version.

### ISSUE THREAD

**Issue by sqrthree** [justjavac/ChromeSnifferPlus#64]
After I upgraded my browser to the latest version, it had no effect whatsoever. but before, it worked well.
### Chrome version:

```
Google Chrome   49.0.2623.75 (Official Build) (64-bit)
Revision    76745cbfbdac04e2fe3204f8b4f96ae7dc6bfcfa-refs/branch-heads/2623@{#561}
OS  Mac OS X 
Blink   537.36 (@76745cbfbdac04e2fe3204f8b4f96ae7dc6bfcfa)
JavaScript  V8 4.9.385.28
Flash   20.0.0.306
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
```

![image](https://cloud.githubusercontent.com/assets/8622362/13658438/e016c28a-e6b1-11e5-832c-896caf8ce762.png)

**Comment by justjavac** [comment]
![image](https://cloud.githubusercontent.com/assets/359395/13659515/55e162f8-e6bd-11e5-9d7c-c474d81d6f8c.png)

我用的 Windows 版的，版本 49.0.2623.87 m。

Chrome 的最新版对插件进行了调整，我也正在看最新的插件文档。

**Comment by MofeLee** [comment]
![image](https://cloud.githubusercontent.com/assets/5069410/13866380/c236a8ae-ecef-11e5-8897-3a1cbc9bcf3b.png)
我的mac可以正常工作，只是显示的形式和以前不一样了

Chrome Version 49.0.2623.87 (64-bit)
MAC 10.11.3

**Comment by justjavac** [comment]
@MofeLee Chrome 升级了
