### ISSUE TITLE
sina 检测出错 显示是Bootstrap 我好奇看了下，其实不是Bootstrap，只是他们自己起了一个叫Bootstrap的文件名

### ISSUE THREAD

**Issue by zminds** [justjavac/ChromeSnifferPlus#73]
![image](https://cloud.githubusercontent.com/assets/1445705/19514629/d432b27e-9626-11e6-9a5e-7e955223139e.png)
[http://js.t.sinajs.cn/t5/pack/js/bootstrap.js](http://js.t.sinajs.cn/t5/pack/js/bootstrap.js)

**Comment by justjavac** [comment]
这就尴尬了。。。。
