### ISSUE TITLE
[Deprecation] chrome.loadTimes() is deprecated

### ISSUE THREAD

**Issue by zhanglianxin** [justjavac/ChromeSnifferPlus#94]
Google Chrome Version 64.0.3282.39 (Official Build) beta (64-bit)

[Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2. https://www.chromestatus.com/features/5637885046816768.
SPDY @ chrome-extension://****/js/detector.js:393

Although it's a warning message, the extension doesn't work normally.

I found this page may be helpful ([Chrome 64 to deprecate the chrome.loadTimes() API](https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated)).

**Comment by justjavac** [comment]
I will fix it https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated#wasfetchedviaspdy
