### ISSUE TITLE
No sniff result on https://www.uxfol.io/

### ISSUE THREAD

**Issue by boviz** [justjavac/ChromeSnifferPlus#99]

**Comment by franklinyu** [comment]
jQuery 3.2.1 has been detected by this extension. Anything else you’re looking for?

**Comment by justjavac** [comment]
![image](https://user-images.githubusercontent.com/359395/36954300-f90b2cd2-205b-11e8-8884-621767571c11.png)

**Comment by boviz** [comment]
Hi,

Now its okay, but did not show me before.
Thanks,
Laszlo
